### ISSUE TITLE
Index doesn't find some particles with macrons

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#55]
some particles that are in the index (ex: ēsa, ēkotē ēkwa ēkota) are not found if written with a macron but are found if they are written with a circumfix.

**Comment by bengodden** [comment]
Here is an example region:

https://dev.kiyanaw.net/transcribe-edit/bengodden:3d93d620-f7b9-11e9-be85-472ce8407922#wavesurfer_9clgbrkce2k

**Comment by aaronfay** [comment]
I have a fix for this ready, the issue was in some logic where there is no `-` in the word, it's not searching for the `^` circumflex version. Will roll out shortly.

**Comment by aaronfay** [comment]
This is fixed in https://github.com/kiyanaw/kiyanaw-backend/commit/e762d77a98d18127de526e9b35b317336043a098.

**Comment by aaronfay** [comment]
Hum, reopening this, some words (êkwa) still not matching [here](https://dev.kiyanaw.net/transcribe-edit/bengodden:3d93d620-f7b9-11e9-be85-472ce8407922#wavesurfer_e88egk6ck4g)

**Comment by aaronfay** [comment]
*Actually* fixed in https://github.com/kiyanaw/kiyanaw-backend/commit/eea2ca34f5feefd4c4ca85f01bfbca9933d97b6d
