### ISSUE TITLE
ē-kī- forms not recognized by index

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#56]
When the kī- past tense marker is added to the ē- conjunct marker, the index fails to retrieve the lemma.

The following region shows the issue clearly:

http://tanisi-20190312204209-hostingbucket-dev.s3-website-us-east-1.amazonaws.com/transcribe-edit/bengodden:3d93d620-f7b9-11e9-be85-472ce8407922#wavesurfer_dk1nc5kln9s

**Comment by aaronfay** [comment]
Fixed in https://github.com/kiyanaw/kiyanaw-backend/commit/e66bd6e17dcb64777bb912b700ab49f33636aa56

**Comment by aaronfay** [comment]
This should be fixed in https://github.com/kiyanaw/kiyanaw-backend/commit/05789861232e45c64808569397bbcd3fa4c2c38b. I've also improved matching on conjunct types in general.
