### ISSUE TITLE
stop submitted English from entering index

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#60]
When a speaker codeswitches to English (or any language but the target language) during speech, we need a way/method to filter this out from being recognized as a new word: this could be programmatically or simply through marking via user input:

nikī-wāpamāw <<Bill Jones walking>> ēkotē mēskanāhk.

**Comment by aaronfay** [comment]
I had thought maybe we would manually flag the words by highlight -> tag of some kind. Still working out how to accomplish this using Quill, will start on this soon.
