### ISSUE TITLE
Full comment not viewable if too long

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#68]
If comment on notification is too long, the whole comment cannot be viewed within the window. See the comment at https://app.kiyanaw.net/transcribe-edit/8a88c830/wavesurfer_1583377226137 for an example.

**Comment by aaronfay** [comment]
Fixed in https://github.com/kiyanaw/kiyanaw-backend/commit/0b9ee94f4ba4146920f365fcc49bfb8a4ae2c213
