### ISSUE TITLE
[Highlighting] not shown on words recognized by the index

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#69]
There is a word I can't make out but I believe it is "anita." I wanted to flag the word for others to review and give input on. Trying to place a flag on the recognized word "anita" will work; however the [brackets] don't show around the word to let others know that there is an issue.

See here for example:

https://app.kiyanaw.net/transcribe-edit/4626c2a0/wavesurfer_o6r32qogvso

**Comment by aaronfay** [comment]
Yeah, there are a few issues around "word matching" that are going to be a part of a larger refactor -- which I may not get to right away. For the time being you could work around it by intentionally misspelling the word and then flag it as an issue.

I'll come back to this when we have a bit more of the indexing sorted out.

**Comment by aaronfay** [comment]
This has been fixed in #88
