### ISSUE TITLE
region reposition not saving

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#72]
If you create a region and then change it in anyway (start time/endtime/stretch/shift/etc) it shows updated but once the next region is created, the original region shifts back to its originally created start time/end time

**Comment by bengodden** [comment]
Exiting the transcription to the main menu then re-entering the transcription will draw the two regions above to the list-of-regions. The original region; however, still has it's original start/end time.

Work-around: delete the region you want to resize and then recreate it. This works.

**Comment by bengodden** [comment]
![regionError](https://user-images.githubusercontent.com/57279900/104834104-954bb600-585a-11eb-9eb7-a195397dad24.jpeg)

I noticed that in the active region, it shows that region #650 is "being edited" but that region #650 doesn't exist in the list - in fact the active region is #648 in both the waveform editor and the list-of-regions. Not sure if this helps, but thought I'd mention it.

**Comment by aaronfay** [comment]
This should be fixed in #85
