### ISSUE TITLE
issue highlighting not working correctly

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#74]
create a region, 
highlight a word and create and issue on it
the [surroundingBrackets] and highlighting do not appear

the highlighting does intermittently appear through the transcription though..

**Comment by aaronfay** [comment]
This should be fixed now. I had added another condition for issue creation, but I didn't add a test for it and I can't remember why it was there 🤦 so keep an eye out for other issues.

This one is tested, so we should be done with it.
