### ISSUE TITLE
Issue highlighting doesn't show on word if recognized by index

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#82]
If a word with issue on it is recognized my the index, the [issue_highlighting] doesn't show on that word.

**Comment by bengodden** [comment]
![issueHighlighting_18Feb2021](https://user-images.githubusercontent.com/57279900/108337536-7199c980-7192-11eb-90df-0003efd4c394.png)

Here is a screenshot of the issue.

**Comment by aaronfay** [comment]
This should be fixed in #88
