### ISSUE TITLE
if regions overlap, incorrect region is displayed in active region

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#83]
If two regions overlap, clicking the timestamp of the second region still only brings the first region to the "active region" area. This area does not update to show the second region (of the overlap) once the play head passes the end of the first region.

**Comment by bengodden** [comment]
It seems this issue is intermittent. Upon exiting and re-entering the transcription, the regions update to show in the active region area correctly based on the play head.

**Comment by aaronfay** [comment]
This appears to be behaviour within the wavesurfer lib and might be out of our control. Closing for now.
