### ISSUE TITLE
Issue highlighting not allowing further text to be entered after

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#86]
If an issue is created on the last word in a region and then text is typed after the word, the new text is added within the highlighting. I have not found a way to get outside the highlighting to add more text to a region after an issue has been created on the last word.

**Comment by aaronfay** [comment]
Thanks for reporting, hoping to make some headway on this soon 🙏🏻

**Comment by aaronfay** [comment]
This is addressed in #88
