### ISSUE TITLE
Region Issues Not updated once Region Resolved

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#87]
Resolved an issue for the first time! Now the region's issue box isn't updating correctly. It shows the issue content from the resolved region but the text from the current region and the number of a different region. See attached image:
![regionHighlightIssue_001](https://user-images.githubusercontent.com/57279900/114910889-436fe900-9dd3-11eb-94ff-fd10c787de78.jpg)

**Comment by bengodden** [comment]
Issue is fixed by exiting to the main menu and reloading the transcription file.

**Comment by aaronfay** [comment]
Yeah, reloading the transcription would re-render the whole list, but it should be a quick fix.

**Comment by aaronfay** [comment]
This should be resolved in an upcoming fix.
