### ISSUE TITLE
Word-Suggestion prevents further editing of the word

### ISSUE THREAD

**Issue by bengodden** [kiyanaw/kiyanaw-backend#89]
Once a word is recognized enough to make suggestions from the FST, the drop down menu prevents further editing of the word. Trying to click into the word to type more merely gives the drop down menu - same goes if the arrow keys are used. Perhaps a button to turn off suggestions? Sometimes I phonetically (syllable-by-syllable) try to write out words that are hard to make out, unfortunately the suggestion box keeps recognizing half the word before I have finish figuring out all the syllables/where the word breaks are and it won't let me type the rest of the word!

**Comment by aaronfay** [comment]
Ah interesting, I know exactly what is causing that. I'll try and patch that up this week. Thanks 🙏🏻

**Comment by aaronfay** [comment]
Just pushed out this change, @bengodden can you try it out when you get a chance and let me know?
